### ISSUE TITLE
Charm of Life I does not have EMC value

### ISSUE THREAD

**Issue by eslachance** [Storkman101/Void-World#10]
It seems I can't complete the "Charm of Life" quests as I did the "Charm of Keeping" ones. While the Charm of Keeping (all levels) have an EMC value, the Charm of Life I does not. Since I can't re-submit other emeralds to get the level 1 charms, I can't complete the Charm of Life II quest.

**Comment by Storkman101** [comment]
Jup, and that bug will be fixed jn the next patch

**Comment by Storkman101** [comment]
is Fixed in the build that will be online this day
