### ISSUE TITLE
Shift+Clicking crafting not counted properly

### ISSUE THREAD

**Issue by eslachance** [Storkman101/Void-World#11]
When using SHIFT+Click to create a stack of items in crafting, items that has multiple item outputs will not be counted properly (it counts one crafting action, not one item). For example, creating fluxducts, after putting the recipe that produces 4 "sets", I'll actually just get 9 crafting operations detected (the first set fully, the other 3 is one per crafting operation instead).

**Comment by Storkman101** [comment]
Hmm, I cant fix that probably. That is something about HQM mod itself (and in the next update it is updated to the newest version). If that doesnt fix the problem I cant fix it, since again it is something with the Mod counting the operations

**Comment by Storkman101** [comment]
I have updated the mod, in the new version like I said but I was not able to test it so far. We will see it in this patch

**Comment by Ratzfaz** [comment]
I think, this issue is a problem to fix. I know this issue since Agrarien Skies (one of the first Modpacks with HQM ) on Minecraft 1.6.4.

**Comment by Storkman101** [comment]
Yeah it has something to do with the Mod itself then like Ratzfaz said is is occuring in multiple maps
