### ISSUE TITLE
No way to get netherrack

### ISSUE THREAD

**Issue by darkrage000** [Storkman101/Void-World#16]
no way to get netherrack or netherbrick. and netherbrick stairs cant be uncrafted. 
no netherbrick means no magma crucible which means no redstone energy items (quest required)

**Comment by Antillar** [comment]
Nether Brick Stairs CAN be uncrafted. Try placing some in the different combinations in the middle slots and in the left slot.
Netherrack itself can be obtained in the First Machines quest, chapter Technical.

**Comment by Storkman101** [comment]
Jup, except when you want to do certain quests before they are supposed to happen. Like the magma crucible for cyrotheum you want it earlier. But if you follow the normal quest line you should get everything when you need it to get

**Comment by darkrage000** [comment]
ok, i suddenly figured out that i needed XP  to run the uncrafting table... stupid me

however, the only place that might give netherrack in the tech quest lkine is where it shows a ?pulverizer? or such, which is locked at present.
