### ISSUE TITLE
jetpack quest wont complete

### ISSUE THREAD

**Issue by darkrage000** [Storkman101/Void-World#17]
i get the quest for jetpacks, make the potato jetpack, says quest complete, go back and they dont recognise me having done it

**Comment by Antillar** [comment]
Well, sure you have sopken to both of them? First, one gives quest to speak to the other, then the other gives quest to craft potato jetpack. So, you may be trying to get reward from the first one.

**Comment by Storkman101** [comment]
Jup. Is this one solved yet or not, then I will close it
