### ISSUE TITLE
project E transmutation table loosing emc in lan world

### ISSUE THREAD

**Issue by bear989** [Storkman101/Void-World#2]
My son and I are doing a play through video series of your modpack but everytime we log out he looses everything in the transmutation table.  Making Co-Op quite broken, or at least annoying.

**Comment by Storkman101** [comment]
Hmm I that is something about lan worlds. It doesnt save other players files correctly. I am planning to make yhe server version of the map this sun/monday so that people can play properly on severs

**Comment by bear989** [comment]
ya I actually tested it in a private mod pack and it doest save his EMC
there either, so it's a project E lan issue apparently.

**Comment by Storkman101** [comment]
If possible I will try to have the server online for manual download tomorrow depends if I have the time for it, otherwise it should be available for manual download on monday and later on the ftb launcher itself

**Comment by bear989** [comment]
ok thanks
