### ISSUE TITLE
HQM detecting times crafted instead of number crafted

### ISSUE THREAD

**Issue by darkrage000** [Storkman101/Void-World#20]
in a few quests where you have to craft a certain number oif items (cobble slabs for an example) it says to craft 128 of them... each craft gives you 6, but the system only counts it as 1 (the actual craft event) so you end up crafting far far far more than 128

**Comment by Antillar** [comment]
So, to add:
1. When I craft 8 conduits with shift, it counts 1 conduit crafted.
2. When I craft 8 conduits without shift, it counts 8 conduits crafted.
3. When I craft 2 times 8 conduits with shift, it counts 2 conduits crafted.
4. When I craft 2 times 8 conduits without shift by crafting one group of 8, then placing it in the inventory, then crafting one more group of 8, and placing that one, it counts 16 conduits crafted.
5. When I craft 2 times 8 conduits without shift by storing first 8 then 16 conduits in the cursor, it gives me 8+16=24 conduits crafted. 

This allows for completion of all Storage+ quests just by crafting each item 16 times.

**Comment by Storkman101** [comment]
It has to do something with the HQM mod sometimes not counting tthe stuff right when you are using shift click Like Antillar said and explained but the fith one I didnt know it did that. Apperantly the HQM counts how many item you have on your cursor instead of the amount crafted
