### ISSUE TITLE
Sugarcane?

### ISSUE THREAD

**Issue by Antillar** [Storkman101/Void-World#21]
Well, it happens that I have no sugarcane on the map. I don't need exactly sugarcane, I need sugar (for body stone for gem armor), but I can't seem to find other way to get it then slaying witches. I will now gust go and kill like 30-50, but I am pretty sure there is the other way, and, as usual, I am doing everything the wrong way I always do :)

**Comment by Storkman101** [comment]
You can get it that way yeah, or you are able to get it with the uncrafting table using books, then paper, then sugercane and then get sugar out of it

**Comment by Antillar** [comment]
Okay, thanks :)

**Comment by Antillar** [comment]
Uncrafting paper gives sawdust+water instead of sugarcane.

**Comment by darkrage000** [comment]
i got a sugar from my mobfarm/witch. uncrafted into sugarcane :)

**Comment by Antillar** [comment]
I also got sugar from witches, so now I just need to uncraft it to sugarcane. Not sure if I need sugarcane now, but I will do that.
