### ISSUE TITLE
player data not transfering

### ISSUE THREAD

**Issue by watergod0187** [Storkman101/Void-World#22]
Every since 1.1.2 player data and projectE data has not been able to be transferred to new maps, I can get my hardcore quests to transfer but not anything else. I have done as you stated several times and tried with several different maps.

**Comment by Luuksie** [comment]
I myself am having the same problem i now made a new world in 1.1.3 but my player data and ProjectE data are not trasferring. if i move my old player data it just resets to a fresh one and that is not supposed to happen.

**Comment by Storkman101** [comment]
Sorry for a late reaction I have been on holiday and my school also started this week so busy with that. AAAAND I forgot my github password and couldnt make a new one. I have to look here what is happening since I dont know it either

**Comment by Luuksie** [comment]
No worry's 
Okay so i made a world in 1.1.2, and now that i thought i needed to update i tried moving the files to a 1.1.3 map, but the ProjectE data is not working, same as the PlayerData, I looked at the player data with NBTexplorer and the game just resets the playerData to a fresh one (i have not looked any further into the ProjectE data).

**Comment by Storkman101** [comment]
That is indeed really strange, and I dont know the problem for it. My way to fix things would be googling the issue because I think this has happened before but in another modpack or just in a personal thingy
