### ISSUE TITLE
cant complete questline

### ISSUE THREAD

**Issue by darkrage000** [Storkman101/Void-World#24]
i have Beginning, City, power Plant, and Smeltry completed

Greenhouse quests (grass block) and (cow head) are still locked
Technical quest (redstone furnace) is still locked
Journal is still locked

**Comment by Antillar** [comment]
So, let's have a look at Storkman's complicated quest parent system:

1. Journal quests open a lot. Seriously, a lot.
2. Journal quests are opened all through other chapters.
3. For the first journal quest you need a "page" being renamed in anvil paperwall from chisel. You can get it in pre-last chapter for 1 emerald. DO NOT PLACE IT!!! I did :(
4. The quest from journal I was stuck at is unlocked in Technical+ from ender conduits quest.
5. How the hell have you completed 640k yellorium quest? This is by far the hardest quest of the map.

**Comment by Storkman101** [comment]
It is indeed the hardest quest in the map, hahaha. Probably in next patch (if you read this) I will lower the cost of yellorium to make it a bit easier to run a reactor and that quest will be easier

**Comment by Antillar** [comment]
I used OpenBlocks Block breaker with constant redstone signal hooked to MFR Block plaser with Redstone Clock from EU and to Vacuum Hopper from OpenBlocks. This setup is commonly known, and is not a 100% legit machine, but perfect EMC farm. Yhis was enough to complete most hardcore quests, and I could deinstall all Blaze EMC grinders to rise my FPS to 40.
