### ISSUE TITLE
[Version 1.1.3] Quest "Too much power" impossible

### ISSUE THREAD

**Issue by Typhoos** [Storkman101/Void-World#27]
Because Vibrant Capacitor Bank aren't detected even when they are full

**Comment by Storkman101** [comment]
Yo thanks for the headsup it is probably a thing to do with NBT, and META data and that is why they are not detected, have to check that. More information will follow later when tested

**Comment by Storkman101** [comment]
woops, still havent fixed this. I will try to update it next patch if I don't forget it
