### ISSUE TITLE
Mushrooms soup quest is bugged in 1.1.5

### ISSUE THREAD

**Issue by ilcalmissimo** [Storkman101/Void-World#30]
i love your idea.i love the mod!!! but in 1.1.5 there's a bug and i can't do any quest!!! do you know the quest which requires 70 cobblestone and some soups???' it's freakin' bugged! when i collect the 70 cobblestone the quest bugs and i can't do it!! here's an image:
![2015-09-16_20 20 26](https://cloud.githubusercontent.com/assets/14317993/9914098/7f24e488-5cb0-11e5-8328-eb7abbd30833.png)

![2015-09-16_20 20 31](https://cloud.githubusercontent.com/assets/14317993/9914108/8a98f872-5cb0-11e5-8d99-ade878c37820.png)

![2015-09-16_20 20 34](https://cloud.githubusercontent.com/assets/14317993/9914116/8fccbf5e-5cb0-11e5-9dfd-374ad4f383e1.png)

**Comment by Storkman101** [comment]
the quest after it is bugged. It is not unlocking his stuff which should happen. You have to hqm edit the quest to go on sadly.

**Comment by Storkman101** [comment]
Ey man I found the actual issue. You have to scroll down the task list, there is another task below it
