### ISSUE TITLE
major bug

### ISSUE THREAD

**Issue by MrAndyPipkin** [Storkman101/Void-World#31]
hi just noticed when putting things in the transmutation table by scrolling mouse wheel, the item remains but the emc value goes up, until you back out the table. you may think that's OK but while your in the table you can take stuff with the duped emc i was able to get unlimited picks dark matter ect with out completing a single quest

**Comment by Storkman101** [comment]
A question, when you reload your world you still have those items? Since something like that happened before but last time it was just a visual bug

**Comment by atahan2000** [comment]
While I was playing third party mod pack (Void World) it suddenly crashed Didn't write anything it went to feedthebeast launcher I changed the folder after that nothing changed. Please help.

(Sorry for my English)
