### ISSUE TITLE
map problem

### ISSUE THREAD

**Issue by lucamerchio** [Storkman101/Void-World#34]
everytime i exit the game and try to re-open the map it doesn't work and i have to start a new game

**Comment by Storkman101** [comment]
I need more info, what happens when you close the game (in the console) and what happens when you open a generated world

**Comment by lucamerchio** [comment]
When I exit is like a normal game but when I try to open the map it says "generating world" and after a minute "disconnecting from the server" and it returns to the main menu

**Comment by Storkman101** [comment]
have you tried a clean install of the pack? And what does the console of your launcher say? I might find more information there, the console is the seperate window where every command and stuff is displayed. You might have to enable that in the settings
