### ISSUE TITLE
No airstrikes

### ISSUE THREAD

**Issue by rasvexes** [Storkman101/Void-World#37]
The air strikes have stopped coming  is that a bug?

**Comment by Storkman101** [comment]
Probably. Already busy with making a more reliable redstone network for those kind of things and more randomness in the time between the strikes. Can you say when did they stop happening

**Comment by rasvexes** [comment]
Or is it because I set it to easy...?

Nothing after the 1st one

On Tue, Nov 3, 2015 at 12:51 AM, Storkman101 notifications@github.com
wrote:

> Probably. Already busy with making a more reliable redstone network for
> those kind of things and more randomness in the time between the strikes.
> Can you say when did they stop happening
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Storkman101/Void-World/issues/37#issuecomment-153080451
> .

## 

_Regards,_
_Shervin Ang_

**Comment by Storkman101** [comment]
yeah, that is the cause of the problem. You will get some later on when you complete some quests
