### ISSUE TITLE
quest book wont open? {server version 1.1.9}

### ISSUE THREAD

**Issue by pyrokilr18** [Storkman101/Void-World#39]
I don't know if anyone else is having this issue but I installed server version 1.1.9 and ran it successfully but when I enter in game in the starting room and try to open the quest book, my game freezes for about 1-2 min then works again but the quest book never comes up. My friend had the same issue as well. I just tested server version 1.1.8 and I was able to open it then. Any help would be appreciated. Thanks.

**Comment by Storkman101** [comment]
For some reason my config folder of the 1.1.9 update that I uploaded got corrupted. So the HQM files are not reading properly. You have to use 1.1.8 for now till the new version comes out
