### ISSUE TITLE
Error while launching

### ISSUE THREAD

**Issue by MisterPeModder** [Storkman101/Void-World#4]
I can't manage to lauch the pack. It says "Error while gathering assets: java.lang.NumberFormatException: For input string: "1391-1710ls" in the console.
Do you know how to fix that?

PS: sorry for my bad english...

**Comment by Storkman101** [comment]
It has to do somethig with the forge version but sadly I do not know how to fix it

**Comment by Storkman101** [comment]
I have updated the forge version to a newer and stable recommended version, hopefully this will fix the problem you have. This forge update will occur in the 1.1.0 patch
