### ISSUE TITLE
door to nether can be held open.

### ISSUE THREAD

**Issue by Kuperus** [Storkman101/Void-World#42]
not sure if it`s intentional, but if you place a block in place where the blocks slide to close the portal room then when the portal closes and you remove the blocks, the portal stays open, you never have to power it again.

**Comment by Storkman101** [comment]
This is the way how pistons work don't they? Some mechanics are just done with some basic redstone, so sometimes it is less stable. Might have to get a refresher on them tho, but I will have to see that.
