### ISSUE TITLE
Pigmen won't spawn

### ISSUE THREAD

**Issue by rensha** [Storkman101/Void-World#5]
used slabs to make a platform about 15-20 blocks away from portal. then made a 16x16 platform then laided another layer of slabs so they turn into full blocks checked with F7 to ensure spawning serfice is correct....annnnd no pigmen....waiting around in survival mode for quite some time....nothing

**Comment by rensha** [comment]
used creative to spawn some....and they instantly disappear o-o

**Comment by Storkman101** [comment]
If you have an way from your portal to the platform extent it after the platform. I probably is still too close to spawn pigmen so you have to be a bit further away

**Comment by Storkman101** [comment]
Hmmm weird, for some reason your world is set to peaceful

**Comment by rensha** [comment]
ah thank you. ill look into commanding it into normal mode then thank you

**Comment by rensha** [comment]
there just clicked the difficulty setting a few times and it fixed it. thank you.

**Comment by rensha** [comment]
ok so it only works for a moment. and then spawning stops. and i have to reload the world. and now its stopped working...i can spawn them now but they don't spawn...odd...well sorry I cant give more info. good luck. (just spawning some works to finish the quest now at least)

**Comment by Storkman101** [comment]
Hmm that is indeed very odd, something messed up my my commandblocks I think. I have to check that later today. But I dont know for sure what happenened because I didnt had any problems before with mobs not spawning. I know someone had this problem, started a new world and it didnt occur

**Comment by Storkman101** [comment]
It should be fixed in one of the newer updates, which is out already I thought it was 1.0.2, had any more troubles?
