### ISSUE TITLE
HQM Quest, Technical > Flux Ducts III

### ISSUE THREAD

**Issue by JarlGiga** [Storkman101/Void-World#8]
crafting task isn't finishing when i make the Redstone Energy Fluxduct, even after it took me a while to find out that i had to use colored redstone blocks to make  the destabilized redstone

**Comment by Storkman101** [comment]
I will have a look on it, thx for the report

**Comment by Storkman101** [comment]
I found the problem, this was also said on the forum and the problem is that it is a detection task since the hqm system cannnot detect stuff that is crafted in a machine
